name: Build, Test, Lint, and Notify

on:
  push:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install

      # 1. Automatisierte Tests (Jest)
      - name: Run Tests
        run: npm test -- --ci

      # 2. Linting (ESLint)
      # - name: Run ESLint
      #   run: npm run lint

      # Build-Schritt
      - name: Build React App
        run: npm run build

      # 5. Discord Benachrichtigung
      - name: Discord Benachrichtigung bei Erfolg
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "✅ Build, Test & Lint erfolgreich für Commit '${{ github.sha }}' auf `${{ github.ref }}`!"}' \
            $DISCORD_WEBHOOK
